export const SUBMITTED = 'SUBMITTED';
export const CHANGE_DATE_BEGIN = 'CHANGE_DATE_BEGIN';
export const CHANGED_DATE_END = 'CHANGED_DATE_END';
export const REQUEST_RESULTS_SUCCESS = 'REQUEST_RESULTS_SUCCESS';
export const REQUEST_RESULTS_FAILED = 'REQUEST_RESULTS_FAILED';
